#!/usr/bin/env node
// Creates the git-ignored `.env` that compose.yaml reads: random secrets and
// loopback port numbers. It never prints a secret.
//
//   node scripts/generate-env.mjs            # refuses to replace an existing file
//   node scripts/generate-env.mjs --force    # replaces it
//   node scripts/generate-env.mjs --out <path>
//
// Ports default to the values below; set KEYCLOAK_PORT, LITELLM_PORT,
// MOCK_UPSTREAM_PORT, POSTGRES_PORT or BROKER_PORT in the environment to
// choose others. 0 lets Docker choose a free port when the service starts;
// a stack whose KEYCLOAK_PORT or LITELLM_PORT is 0 then needs the port Docker
// chose as KEYCLOAK_PUBLISHED_PORT or LITELLM_PUBLISHED_PORT before the
// broker starts (README, "Ports"), which the tests do.
import { randomBytes } from "node:crypto";
import { chmodSync, existsSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const force = args.includes("--force");
const outIndex = args.indexOf("--out");
const out =
  outIndex >= 0 && args[outIndex + 1]
    ? resolve(args[outIndex + 1])
    : join(here, "..", ".env");

const PORTS = {
  KEYCLOAK_PORT: 18080,
  LITELLM_PORT: 14000,
  MOCK_UPSTREAM_PORT: 18090,
  POSTGRES_PORT: 15432,
  BROKER_PORT: 18070,
};

function port(name) {
  const value = process.env[name] ?? String(PORTS[name]);
  const number = Number(value);
  if (
    !/^\d+$/.test(value) ||
    (number !== 0 && number < 1024) ||
    number > 65535
  ) {
    process.stderr.write(
      `${name} must be a port from 1024 to 65535, or 0 for one Docker chooses\n`,
    );
    process.exit(2);
  }
  return number;
}

// Hex keeps every value safe in a URL, a shell, and a compose .env file.
const secret = (bytes = 32) => randomBytes(bytes).toString("hex");

if (existsSync(out) && !force) {
  process.stderr.write(`${out} exists; pass --force to replace it\n`);
  process.exit(1);
}

const lines = [
  "# Generated by scripts/generate-env.mjs for the local enterprise reference",
  "# stack. Git-ignored: never commit, print, or share this file.",
  ...Object.keys(PORTS).map((name) => `${name}=${port(name)}`),
  `KEYCLOAK_ADMIN_PASSWORD=${secret()}`,
  `POSTGRES_PASSWORD=${secret()}`,
  // LiteLLM requires the master key to start with sk-. The salt key encrypts
  // stored provider credentials and must not change while the database lives.
  `LITELLM_MASTER_KEY=sk-${secret()}`,
  `LITELLM_SALT_KEY=${secret()}`,
  `MOCK_UPSTREAM_API_KEY=${secret()}`,
  `REFERENCE_ALICE_PASSWORD=${secret(18)}`,
  `REFERENCE_BOB_PASSWORD=${secret(18)}`,
  "",
];

writeFileSync(out, lines.join("\n"), { mode: 0o600 });
chmodSync(out, 0o600); // `mode` applies only when the file is created
process.stdout.write(`wrote ${out} (mode 600)\n`);
